version: "3.9"

services:
  redis:
    container_name: shortie-redis-cache
    image: redis/redis-stack-server:latest
    restart: always
    entrypoint: redis-stack-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  api:
    container_name: shortie-api-server
    build: .
    depends_on:
      - redis
    ports:
      - '8000:8000'
    environment:
      - ENV=LOCAL_DOCKER
      - REDIS_HOST=shortie-redis-cache
      - REDIS_OM_URL=redis://@shortie-redis-cache:6379

volumes:
  redis:
    driver: local
