name: Dispatch Workflow
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'main'
      - 'master'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        path: base
    - uses: actions/checkout@v3
      with:
        path: target

    - run: cat ${{ github.workspace}}/base/.github/workflows/custom-action.yml
    - run: cat ${{ github.workspace}}/target/.github/workflows/custom-action.yml
    # - name: Diff k8s manifest changes
    #   uses: rafaelbroseghini/diff@main
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
